sudo: false
language: cpp
compiler:
    - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - pip install tox-travis --user
python:
  - "2.7"
  - "3.4"
script:
  - CC=g++-4.8 python2 setup.py test
  - tox
